name: 'airbyte_shopify'
version: '0.1.0'
require-dbt-version: ['>=1.0.0']
config-version: 2
profile: 'default'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbyte_shopify:
    materialized: table
    tmp:
      materialized: view

vars:
  airbyte_shopify:
    customers: "{{ source('airbyte_shopify','customers') }}"
    customers_default_address: "{{ source('airbyte_shopify','customers_default_address') }}"
    order_refunds: "{{ source('airbyte_shopify','order_refunds') }}"
    order_refunds_refund_line_items: "{{ source('airbyte_shopify','order_refunds_refund_line_items') }}"
    orders: "{{ source('airbyte_shopify','orders') }}"
    orders_line_items: "{{ source('airbyte_shopify','orders_line_items') }}"
    orders_shipping_address: "{{ source('airbyte_shopify','orders_shipping_address') }}"
    orders_shipping_lines: "{{ source('airbyte_shopify','orders_shipping_lines') }}"
    products: "{{ source('airbyte_shopify','products') }}"
    products_variants: "{{ source('airbyte_shopify','products_variants') }}"
    transactions: "{{ source('airbyte_shopify','transactions') }}"
