version: 2

sources:
  - name: airbyte_shopify
    schema: "{{ var('shopify_schema', 'shopify') }}"
    database: "{% if target.type != 'spark'%}{{ var('shopify_database', target.database) }}{% endif %}"
    tables:
      - name: customers
      - name: orders_line_items
      - name: order_refunds_refund_line_items
      - name: orders
      - name: orders_shipping_address
      - name: orders_shipping_lines
      - name: products
      - name: products_variants
      - name: order_refunds
      - name: transactions

models:
  - name: shopify__customers
    description: "A table storing all customer info"
    columns:
      - name: customer_id
        description: "The unique identifier for the customer"
        tests:
          - unique
          - not_null

  - name: shopify__orders
    description: "A table storing all orders"
    columns:
      - name: order_id
        description: "The unique identifier for the order"
        tests:
          - unique
          - not_null

  - name: shopify__products
    description: "A table storing all products"
    columns:
      - name: product_id
        description: "The unique identifier for the product"
        tests:
          - unique
          - not_null

  - name: shopify__transactions
    description: "A table storing all transactions"
    columns:
      - name: transaction_id
        description: "The unique identifier for the transaction"
        tests:
          - unique
          - not_null
